const tankTheCar = (arg1 = "diesel", arg2 = "XL") => console.log((`Заправка для ${arg2} авто, тип палива ${arg1}`))
tankTheCar("gas","S")
tankTheCar("gas","M")
tankTheCar("gas","L")
tankTheCar("gas","XL")
tankTheCar("diesel","S")
tankTheCar("diesel","M")
tankTheCar("diesel","L")
tankTheCar()